MobileHelpMe_rails/config/routes.rb
MobileHelpMeRails::Application.routes.draw do

  # intended for web-based admin console
  namespace :admin do
    resources :categories
  end

  # intended for JSON output via REST calls
  resources :task_requests, :except => [:new, :edit, :destroy]
  resources :users        , :except => [:new, :edit, :destroy] do
    # TODO: implement these as nested resources
    # resources :payments
    # resources :feedbacks
    # resources :problem_reports
  end

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

MobileHelpMe_rails/app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
end

MobileHelpMe_rails/app/models/task_request.rb
class TaskRequest < ActiveRecord::Base
end

MobileHelpMe_rails/app/models/user.rb
class User < ActiveRecord::Base
end

MobileHelpMe_rails/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  # GET /admin/categories
  # GET /admin/categories.xml
  def index
    @admin_categories = Admin::Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.xml
  def show
    @admin_category = Admin::Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.xml
  def new
    @admin_category = Admin::Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @admin_category = Admin::Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.xml
  def create
    @admin_category = Admin::Category.new(params[:admin_category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to(@admin_category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @admin_category, :status => :created, :location => @admin_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.xml
  def update
    @admin_category = Admin::Category.find(params[:id])

    respond_to do |format|
      if @admin_category.update_attributes(params[:admin_category])
        format.html { redirect_to(@admin_category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.xml
  def destroy
    @admin_category = Admin::Category.find(params[:id])
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to(admin_categories_url) }
      format.xml  { head :ok }
    end
  end
end

MobileHelpMe_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

MobileHelpMe_rails/app/controllers/task_requests_controller.rb
class TaskRequestsController < ApplicationController
  # GET /task_request.js
  def index
    @task_request = TaskRequest.all
  
    respond_to do |format|
      # format.html # index.html.erb
      format.js  { render :json => @task_request }
    end
  end
  
  # GET /task_request/1.js
  def show
    @task_request = TaskRequest.find(params[:id])
  
    respond_to do |format|
      # format.html # show.html.erb
      format.js  { render :json => @task_request }
    end
  end

  # POST /task_request.js
  def create
    @task_request = TaskRequest.new(params[:task_request])

    respond_to do |format|
      if @task_request.save
        # format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.js  { render :json => @task_request, :status => :created, :location => @task_request }
      else
        # format.html { render :action => "new" }
        format.js  { render :json => @task_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /task_request/1.js
  def update
    @task_request = TaskRequest.find(params[:id])
  
    respond_to do |format|
      if @task_request.update_attributes(params[:task_request])
        # format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.js  { head :ok }
      else
        # format.html { render :action => "edit" }
        format.js  { render :json => @task_request.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # # DELETE /task_request/1.js
  # def destroy
  #   @task_request = TaskRequest.find(params[:id])
  #   @task_request.destroy
  # 
  #   respond_to do |format|
  #     # format.html { redirect_to(task_requests_url) }
  #     format.js  { head :ok }
  #   end
  # end
end

MobileHelpMe_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users.js
  def index
    @users = User.all

    respond_to do |format|
      # format.html # index.html.erb
      format.js  { render :js => @users }
    end
  end

  # GET /users/1.js
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      # format.html # show.html.erb
      format.js  { render :js => @user }
    end
  end

  # POST /users.js
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.js  { render :js => @user, :status => :created, :location => @user }
      else
        # format.html { render :action => "new" }
        format.js  { render :js => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1.js
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        # format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.js  { head :ok }
      else
        # format.html { render :action => "edit" }
        format.js  { render :js => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # # DELETE /users/1.js
  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy
  # 
  #   respond_to do |format|
  #     # format.html { redirect_to(users_url) }
  #     format.js  { head :ok }
  #   end
  # end
end

MobileHelpMe_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

MobileHelpMe_rails/app/views/admin/categories/_form.html.erb
<%= form_for(@admin_category) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MobileHelpMe_rails/app/views/admin/categories/edit.html.erb
<h1>Editing admin_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_category %> |
<%= link_to 'Back', admin_categories_path %>

MobileHelpMe_rails/app/views/admin/categories/index.html.erb
<h1>Listing admin_categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_categories.each do |admin_category| %>
  <tr>
    <td><%= admin_category.title %></td>
    <td><%= link_to 'Show', admin_category %></td>
    <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
    <td><%= link_to 'Destroy', admin_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_admin_category_path %>

MobileHelpMe_rails/app/views/admin/categories/new.html.erb
<h1>New admin_category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

MobileHelpMe_rails/app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @admin_category.title %>
</p>


<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>

MobileHelpMe_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileHelpMeRails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>